export enum TestStatus {
    PENDING = 0,
    SCHEDULED = 1,
    RUNNING = 2,
    COMPLETED = 3,
    ABORTED = 4,
    FAILED = 5,
    TIMED_OUT = 6,
    CANCELLED = 7,
}

export enum TestSource {
    BASIC = 'basic',
    ADVANCED = 'advanced',
    UPLOAD = 'upload',
    API = 'api',
    CLI = 'cli',
    AGENT = 'agent',
    UNKNOWN = 'unknown',
}

export class TestConfig {
    test_id: string;
    url?: string;
    browser?: string;
    source?: TestSource | TestSource.UNKNOWN;
    name?: string | null;
    description?: string | null;
    owner?: string | null; // user id or email
    cli_command?: string | null;
    device?: string | null;
    status?: TestStatus | null = TestStatus.PENDING;
    created_at: number = Math.floor(Date.now() / 1000);
    // all the cli options for the test, these would be overrides of the default options
    headers?: string | null;
    cookies?: string | null;
    flags?: string | null;
    block_domains?: string | null;
    block?: string | null;
    firefox_prefs?: string | null;
    cpu_throttle?: number | null;
    connection_type?: string | null;
    width?: number | null;
    height?: number | null;
    frame_rate?: number | null;
    disable_js?: boolean | null;
    debug?: boolean | null;
    auth?: string | null;
    timeout?: number | null;

    constructor() {
        this.test_id = this.generateUUID();
    }

    /// <summary>
    /// Create a TestConfig from a config file that is
    /// generated by Telescope agent.
    /// </summary>
    /// <param name="config">The config object</param>
    /// <returns>The TestConfig object</returns>
    static fromConfig(testId: string, config: Record<string, any>): TestConfig {
        const testConfig = new TestConfig();
        // may need to parse from cli command if available
        testConfig.test_id = testId;
        testConfig.url = config.url || '';
        testConfig.created_at = Math.floor(new Date(config.date).getTime() / 1000) || Math.floor(Date.now() / 1000);
        testConfig.browser = config.options.browser || '';
        testConfig.source = config.source || TestSource.UNKNOWN;
        testConfig.name = config.name || null;
        testConfig.description = config.description || null;
        testConfig.owner = config.owner || null;
        testConfig.cli_command = config.cli_command || null;
        testConfig.device = config.options.device || null;
        testConfig.headers = config.options.headers || null;
        testConfig.cookies = config.options.cookies || null;
        testConfig.flags = config.options.flags || null;
        testConfig.block_domains = config.options.block_domains || null;
        testConfig.block = config.options.block || null;
        testConfig.firefox_prefs = config.browserConfig.firefox_prefs || null;
        testConfig.cpu_throttle = config.options.cpu_throttle || null;
        testConfig.connection_type = config.options.connection_type || null;
        testConfig.width = config.browserConfig.viewport.width || null;
        testConfig.height = config.browserConfig.viewport.height || null;
        testConfig.frame_rate = config.options.frame_rate || null;
        testConfig.disable_js = config.options.disable_js || null;
        testConfig.debug = config.options.debug || null;
        testConfig.auth = config.options.auth || null;
        testConfig.timeout = config.options.timeout || null;
        return testConfig;
    }

    /// <summary>
    /// Create a TestConfig from a input object that is sent to the API
    /// via the web form or the API endpoint directly.
    /// </summary>
    /// <param name="data">The input object</param>
    /// <returns>The TestConfig object</returns>
    static fromInput(data: Record<string, any>): TestConfig {
        const testConfig = new TestConfig();
        testConfig.test_id = testConfig.generateUUID();
        testConfig.url = data.url || '';
        testConfig.browser = data.browser || '';
        testConfig.source = data.source || null;
        testConfig.name = data.name || null;
        testConfig.description = data.description || null;
        testConfig.owner = data.owner || null;
        testConfig.cli_command = data.cli_command || null;
        testConfig.device = data.device || null;
        testConfig.headers = data.headers || null;
        testConfig.cookies = data.cookies || null;
        testConfig.flags = data.flags || null;
        testConfig.block_domains = data.block_domains || null;
        testConfig.block = data.block || null;
        testConfig.firefox_prefs = data.firefox_prefs || null;
        testConfig.cpu_throttle = data.cpu_throttle || null;
        testConfig.connection_type = data.connection_type || null;
        testConfig.width = data.width || null;
        testConfig.height = data.height || null;
        testConfig.frame_rate = data.frame_rate || null;
        testConfig.disable_js = data.disable_js || null;
        testConfig.debug = data.debug || null;
        testConfig.auth = data.auth || null;
        testConfig.timeout = data.timeout || null;
        return testConfig;
    }

    private generateUUID(): string {
        let date_ob = new Date();
        // adjust 0 before single digit value
        let date = ('0' + date_ob.getDate()).slice(-2);
        let month = ('0' + (date_ob.getMonth() + 1)).slice(-2);
        let year = date_ob.getFullYear();
        let hour = ('0' + date_ob.getHours()).slice(-2);
        let minute = ('0' + date_ob.getMinutes()).slice(-2);
        let second = ('0' + date_ob.getSeconds()).slice(-2);
        return year + '_' + month + '_' + date + '_' + hour + '_' + minute + '_' + second + '_' + generatePseudoRandomUUID();

        function generatePseudoRandomUUID(): string {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                const r = Math.random() * 16 | 0;
                const v = c === 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }
    }

    isValid(): boolean {
        return this.url !== '' && this.browser !== '';
    }

    async saveToD1(env: any): Promise<any | null> {
        try {
            const stmt = env.DB.prepare(`
    INSERT INTO tests (
      test_id, 
      name, 
      source, 
      owner, 
      url, 
      browser, 
      device, 
      headers, 
      cookies, 
      flags, 
      block_domains, 
      block, 
      firefox_prefs, 
      cpu_throttle, 
      connection_type, 
      width, 
      height, 
      frame_rate, 
      disable_js, 
      debug, 
      auth, 
      timeout, 
      status, 
      created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);
            await stmt.bind(
                this.test_id,
                this.name,
                this.source,
                this.owner,
                this.url,
                this.browser,
                this.device,
                this.headers,
                this.cookies,
                this.flags,
                this.block_domains,
                this.block,
                this.firefox_prefs,
                this.cpu_throttle,
                this.connection_type,
                this.width,
                this.height,
                this.frame_rate,
                this.disable_js,
                this.debug,
                this.auth,
                this.timeout,
                this.status,
                this.created_at
            ).run();
            return stmt.changes;
        } catch (error) {
            console.error('Failed to save test:', error);
            return null;
        }
    }
}